// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/droot/godocbot/pkg/client/clientset/versioned/typed/code/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCodeV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCodeV1alpha1) PullRequests(namespace string) v1alpha1.PullRequestInterface {
	return &FakePullRequests{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCodeV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
