// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PullRequestListerExpansion allows custom methods to be added to
// PullRequestLister.
type PullRequestListerExpansion interface{}

// PullRequestNamespaceListerExpansion allows custom methods to be added to
// PullRequestNamespaceLister.
type PullRequestNamespaceListerExpansion interface{}
