// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/droot/godocbot/pkg/apis/code/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PullRequestLister helps list PullRequests.
type PullRequestLister interface {
	// List lists all PullRequests in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.PullRequest, err error)
	// PullRequests returns an object that can list and get PullRequests.
	PullRequests(namespace string) PullRequestNamespaceLister
	PullRequestListerExpansion
}

// pullRequestLister implements the PullRequestLister interface.
type pullRequestLister struct {
	indexer cache.Indexer
}

// NewPullRequestLister returns a new PullRequestLister.
func NewPullRequestLister(indexer cache.Indexer) PullRequestLister {
	return &pullRequestLister{indexer: indexer}
}

// List lists all PullRequests in the indexer.
func (s *pullRequestLister) List(selector labels.Selector) (ret []*v1alpha1.PullRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PullRequest))
	})
	return ret, err
}

// PullRequests returns an object that can list and get PullRequests.
func (s *pullRequestLister) PullRequests(namespace string) PullRequestNamespaceLister {
	return pullRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PullRequestNamespaceLister helps list and get PullRequests.
type PullRequestNamespaceLister interface {
	// List lists all PullRequests in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.PullRequest, err error)
	// Get retrieves the PullRequest from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.PullRequest, error)
	PullRequestNamespaceListerExpansion
}

// pullRequestNamespaceLister implements the PullRequestNamespaceLister
// interface.
type pullRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PullRequests in the indexer for a given namespace.
func (s pullRequestNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.PullRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PullRequest))
	})
	return ret, err
}

// Get retrieves the PullRequest from the indexer for a given namespace and name.
func (s pullRequestNamespaceLister) Get(name string) (*v1alpha1.PullRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pullrequest"), name)
	}
	return obj.(*v1alpha1.PullRequest), nil
}
