// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	code_v1alpha1 "github.com/droot/godocbot/pkg/apis/code/v1alpha1"
	versioned "github.com/droot/godocbot/pkg/client/clientset/versioned"
	internalinterfaces "github.com/droot/godocbot/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/droot/godocbot/pkg/client/listers/code/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PullRequestInformer provides access to a shared informer and lister for
// PullRequests.
type PullRequestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PullRequestLister
}

type pullRequestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPullRequestInformer constructs a new informer for PullRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPullRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPullRequestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPullRequestInformer constructs a new informer for PullRequest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPullRequestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CodeV1alpha1().PullRequests(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CodeV1alpha1().PullRequests(namespace).Watch(options)
			},
		},
		&code_v1alpha1.PullRequest{},
		resyncPeriod,
		indexers,
	)
}

func (f *pullRequestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPullRequestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pullRequestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&code_v1alpha1.PullRequest{}, f.defaultInformer)
}

func (f *pullRequestInformer) Lister() v1alpha1.PullRequestLister {
	return v1alpha1.NewPullRequestLister(f.Informer().GetIndexer())
}
